version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt 
      - pip pylint

  pre_build:
    commands:
      - echo "Building the project..."
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py
      - pylint $CODEBUILD_SRC_DIR/Stark/*.py
      - pylint --disable=R0903,E1101 $CODEBUILD_SRC_DIR/conversation/*.py

post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
